### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by planemad** [savethemap/savethemap.in#6]
The headline purple color has a [low contrast](http://snook.ca/technical/colour_contrast/colour.html#fg=A07FBF,bg=FFFFFF) against white. A more darker `#6A468D` seems to pass the test.

cc @karthikb351 

For future accessibility checks:
- http://achecker.ca/checker/index.php
- http://www.checkmycolours.com

**Comment by karthikb351** [comment]
Fixed in 819433dc61cd9b2beac23d4c630c3dcf0858f767 and c3c0e2159f9a1a9cd618e2eb8e2ec3dd4771816e
