### ISSUE TITLE
Email response template

### ISSUE THREAD

**Issue by planemad** [savethemap/savethemap.in#9]
Many have been asking for this to quickly send a mail to the MHA. The downside of this is it will cause people to not read the draft, on the upside, it can quickly get more numbers and raise awareness of the issue.

If someone can draft a template, lets add it to the site ASAP.

cc @karthikb351

**Comment by planemad** [comment]
Here is one https://gist.github.com/planemad/34c63b097605024485370c1c54b59394

**Comment by srikanthlogic** [comment]
https://datameet.hackpad.com/Template-for-Response-Email-gGXKFBd2tsN is collaboration hackpad

**Comment by NishaT** [comment]
There is a working draft on the hackpad. I'll all for lots of numbers of
emails but we should be a little deliberate. This isn't as simple as saying
NO to the bill, we don't want to be swept up in anti national security
stance. So let's talk about it tomorrow and over the weekend and get some
language that will make sense and get the suggestions clear and crisp and
then create an automatic letter. Then we can do a hard push next week to
fill their inboxes.

Til then we can have them write a testimonial type of letter (which would
make it more time consuming) but people can say "this bill will affect my
life in this way" will be helpful to the campaign and to promote an
understanding of the legislation.

Nisha

On Wed, May 11, 2016 at 12:16 AM, Srikanth L notifications@github.com
wrote:

> https://datameet.hackpad.com/Template-for-Response-Email-gGXKFBd2tsN is
> collaboration hackpad
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/savethemap/savethemap.in/issues/9#issuecomment-218252703,
> or mute the thread
> https://github.com/notifications/unsubscribe/AC0kOBTK_X9r20aqRfdtbIkXTe32bUl0ks5qANKggaJpZM4IaL35
> .

## 

Nisha Thompson
Mobile: 962-061-2245

**Comment by srikanthlogic** [comment]
Also, instead of a single generic email template, it would be nice to have templates for 
1) An individual citizen
2) Business' / commercial user using maps
3) Nonprofit / academicians, researchers using maps for impact.

and have the reasons from each user prespective.

**Comment by srikanthlogic** [comment]
Fixed in #15
